baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'erin on the interwebs'
theme = 'owo'
titleCaseStyle = 'none'

[[params.webring]]
image = "/img/ring/notnite.png"
url = "https://notnite.com"

[[params.webring]]
image = "/img/ring/adryd.png"
url = "https://adryd.com"

[[params.webring]]
image = "/img/ring/espi.png"
url = "https://espi.me"

[[params.webring]]
image = "/img/ring/mary.png"
url = "https://coolmathgames.tech"

[[params.webring]]
image = "/img/ring/philo.png"
url = "https://philo.gay"

[[params.webring]]
image = "/img/ring/88x31.png"
url = "https://eightyeightthirty.one"

[[params.webring]]
image = "/img/ring/skip.png"
url = "https://skip.house"

[[params.webring]]
image = "/img/ring/elixire.gif"
url = "https://elixi.re"

[[params.webring]]
image = "/img/ring/haylin.png"
url = "https://hayl.in"

[[params.webring]]
image = "/img/ring/retr0id.gif"
url = "https://www.da.vidbuchanan.co.uk"
